import type { Move } from './types'

export const initialMoves: Record<string, Move> = {

  enrolldeposit: {
    title: 'Pay your enrollment deposit',
    category: 'enrollment',
    consequence: 'Your spot is released to the waitlist. Most schools will not reinstate it.',
    daysUntil: 3,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    steps: [
      'Log into your admissions portal — the same one where you received your acceptance letter.',
      'Find "Enrollment Deposit" or "Confirm Enrollment" — usually under a banner or checklist on the home screen.',
      'Pay the deposit (typically $200–$500). It is non-refundable but is credited toward your first tuition bill.',
      'Screenshot or download the confirmation page immediately after payment.',
      'Check your email for a confirmation — save it. It is proof of your enrolled status and unlocks your housing portal.',
    ],
    whatToGather: [
      'Admissions portal login',
      'Credit or debit card',
      'Acceptance letter (you may need your applicant ID)',
    ],
    ifWrongGoesWrong: 'If the portal is down or payment fails, call the Admissions Office directly — do not wait for email support. Explain the technical issue and ask them to note the date and time you attempted. Most schools will honor the deadline if you can show proof of a failed attempt.',
    peerInsight: '"I assumed the May 1 deadline was soft. It was not. I had to appeal for two weeks to get my spot back — they almost did not reinstate it." — Transfer student, Cal State to RISD',
    ai: 'May 1 is National Decision Day — the standard deadline most colleges use. Some schools set earlier deadlines for housing or financial aid priority. Check your specific portal, not just the national date. First-gen students miss this step more than any other because no one explicitly tells you that confirming admission and paying a deposit are two separate things.',
  },

  fafsa: {
    title: 'Complete and verify your FAFSA',
    category: 'financial',
    consequence: 'You lose your place in the financial aid queue. State and school grants run out — federal Pell Grant may still be available, but institutional grants will not be.',
    daysUntil: 12,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    steps: [
      'Go to studentaid.gov — the only official FAFSA site.',
      'Create or log in with your FSA ID. Your Social Security Number is required.',
      'Select the correct award year — choose the year you will start college.',
      'Link your IRS tax data using the IRS Data Retrieval Tool inside the form — this auto-fills your income information and reduces errors.',
      'Add your school\'s Federal School Code so they receive your results directly (search at studentaid.gov/school-search).',
      'Submit, then log back in 3–5 days later to check if you were selected for "verification" — a common additional step requiring extra documents.',
    ],
    whatToGather: [
      'FSA ID (create at studentaid.gov if you do not have one)',
      'Social Security Number',
      'Prior year tax returns — yours and your parents\' if you are a dependent student',
      'Bank account information',
      'Federal School Code for your enrolled school',
    ],
    ifWrongGoesWrong: 'If you are selected for verification, your financial aid is frozen until you submit the required documents to your school\'s financial aid office. Go in person if possible — email queues are slow during peak season. Bring originals and copies.',
    peerInsight: '"My aid was held for verification and I only found out by logging in by accident. I almost missed the deadline to submit supporting documents." — First-gen student, Brown University',
    ai: 'The high school class of 2021 left $3.75 billion in federal Pell Grant aid unclaimed because 1.7 million students did not file the FAFSA. The most common reason is not missing the federal deadline — it is missing the school\'s earlier priority deadline, which is when institutional grants are distributed. The federal deadline is June 30. Your school\'s priority deadline is usually February or March.',
  },

  aidaccept: {
    title: 'Accept your financial aid package',
    category: 'financial',
    consequence: 'Grants and loans are cancelled. You may need to reapply, and the same package is not guaranteed to be available.',
    daysUntil: 18,
    dependsOn: ['fafsa'],
    urgency: 'critical',
    done: false,
    steps: [
      'Log into your school\'s student financial services portal — separate from the admissions portal.',
      'Find your financial aid award letter under "Award Summary" or "Financial Aid Offer."',
      'Read each line carefully: "Grants" are free money. "Loans" must be repaid with interest. "Work-study" requires you to get a campus job.',
      'Accept grants and scholarships in full. Be deliberate about how much in loans you accept — you do not have to accept the full offered amount.',
      'If your package seems insufficient or does not reflect your actual financial situation, request a Professional Judgment review before accepting. This is a formal appeal.',
      'Complete entrance counseling and sign your Master Promissory Note at studentaid.gov if accepting any federal loans.',
    ],
    whatToGather: [
      'Student financial services portal login',
      'Your financial aid award letter',
      'Your Expected Family Contribution (EFC) or Student Aid Index (SAI)',
    ],
    ifWrongGoesWrong: 'If your package does not cover your costs, you have the right to appeal. Write a formal letter to the financial aid office explaining what changed in your financial situation. Appeals are more likely to succeed when you provide documentation: a job loss letter, medical bills, or a change in family circumstances.',
    peerInsight: '"I accepted all my loans because I thought I was supposed to take everything offered. I later learned I could have taken less. Read every line before you click accept." — First-gen student, UCLA',
    ai: 'Financial aid award letters are notoriously difficult to read because each school formats them differently. The term "self-help aid" means loans, not grants. "Expected family contribution" does not mean your family will actually pay that amount. If anything is unclear, call the financial aid office directly and ask them to explain each line.',
  },

  housingdeposit: {
    title: 'Submit your housing deposit and preferences',
    category: 'housing',
    consequence: 'You are placed at the bottom of the housing queue. Many students are left without on-campus housing and must find off-campus options on short notice.',
    daysUntil: 21,
    dependsOn: ['enrolldeposit'],
    urgency: 'soon',
    done: false,
    steps: [
      'Log into your school\'s housing portal — this is a separate system from the admissions portal.',
      'Pay the housing deposit (typically $200–$300, applied to your housing bill).',
      'Complete your housing preferences form: roommate preferences, room type, quiet or substance-free floors.',
      'If the school offers roommate matching, fill out the compatibility questionnaire honestly — the algorithm uses it.',
      'Note when housing assignments are sent — typically 6–8 weeks after the deposit deadline.',
      'If you are placed on a housing waitlist, contact the housing office directly and ask for your waitlist number.',
    ],
    whatToGather: [
      'Housing portal login (separate from admissions)',
      'Payment method',
      'Roommate contact info if you have someone in mind',
    ],
    ifWrongGoesWrong: 'If you miss the deadline and end up on a waitlist, start looking at off-campus housing immediately as a backup. Contact the housing office weekly — spots open up as students change plans. International students especially should not wait passively: the off-campus rental market near universities is competitive and has active scammers targeting students unfamiliar with U.S. rental norms.',
    peerInsight: '"I submitted my housing deposit one day late and ended up in a temporary triple for a month. Start early — the portal was slow and it took me three tries to submit payment." — International student, RISD',
    ai: 'Housing deposits are often due within days of the enrollment deposit — sometimes the same day. Check the housing portal the moment you confirm enrollment. International students should prioritize on-campus housing: the scam risk in off-campus student housing markets is real. Fraudulent listings on Craigslist and Facebook Marketplace specifically target students who are booking sight-unseen from abroad.',
  },

  orientation: {
    title: 'Register for orientation',
    category: 'enrollment',
    consequence: 'You lose course registration priority. Some schools do not allow students who miss orientation to register for classes until all other students have picked their schedules.',
    daysUntil: 30,
    dependsOn: ['enrolldeposit'],
    urgency: 'soon',
    done: false,
    steps: [
      'Log into the orientation registration system — usually linked from your admitted student portal or sent by email after your deposit.',
      'Select your session. International students: look specifically for international student orientation, which runs the week before general orientation.',
      'Note any pre-orientation tasks: immunization records, placement tests, financial aid checklists. These are often prerequisites for advising and course registration.',
      'Confirm attendance and add the dates to your calendar.',
      'If you cannot attend your assigned session, contact orientation services immediately to request a transfer to another date.',
    ],
    whatToGather: [
      'Admitted student portal login',
      'Immunization records (check requirements in advance — schools vary)',
      'Academic transcript for placement assessment',
    ],
    ifWrongGoesWrong: 'If you miss orientation entirely, contact your school\'s Dean of Students office — not just the orientation office. They can connect you directly to an academic advisor so you can still register for courses before the semester starts.',
    peerInsight: '"International orientation covered things general orientation assumed you already knew. Go to both if you can." — International student, Columbia',
    ai: 'Course registration happens during or immediately after orientation. The best sections — small classes, popular professors, convenient time slots — fill within hours of registration opening. Arriving at orientation with a course list already prepared is the difference between your ideal schedule and one built from leftovers.',
  },

  i20: {
    title: 'Request your I-20 from your DSO',
    category: 'visa',
    consequence: 'Without your I-20, your visa appointment cannot be booked. Late I-20 requests routinely push arrival dates past the start of classes.',
    daysUntil: 8,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    steps: [
      'Find your DSO by searching "[school name] DSO" or "International Students Office" in your university portal.',
      'Email your DSO — do not walk in or call first. Subject line exactly: "I-20 request — [Full Name] — [Student ID] — arriving [date]"',
      'Body: state your program name, intended start date, and confirm documents are attached.',
      'Attach in one email: acceptance letter, financial proof showing 12 months of tuition plus living costs, and your passport photo page.',
      'Wait 3–5 business days. If no response, forward your original email with "Following up" added to the subject line.',
      'When received, verify your name, program dates, and school address are exactly correct before booking your visa appointment.',
    ],
    whatToGather: [
      'Acceptance letter',
      'Bank statement or financial sponsor letter (must show sufficient funds)',
      'Passport photo page',
      'Student ID number',
    ],
    ifWrongGoesWrong: 'If your I-20 has an error — wrong name spelling, wrong program dates, wrong school address — contact your DSO immediately and request a corrected document before your visa appointment. Do not attend a visa interview with an incorrect I-20. Consular officers flag discrepancies and will deny the application.',
    peerInsight: '"The subject line formula got me a response in 36 hours. My roommate sent a vague email and waited three weeks." — Min-jun K., RISD 2nd year',
    ai: 'Peak I-20 request season is June–July when DSO offices are processing hundreds of requests simultaneously. Emailing in April or early May puts you significantly ahead of that queue. For students from countries with historically longer visa processing times — India, China, Nigeria — earlier is not just preferable, it is critical. Visa appointments in those countries book out 60 or more days in advance.',
  },

  sevis: {
    title: 'Pay your SEVIS fee',
    category: 'visa',
    consequence: 'Your visa application is invalid without SEVIS payment confirmation. The fee is non-refundable — paying on an unofficial site means you lose $350 and must pay again.',
    daysUntil: 14,
    dependsOn: ['i20'],
    urgency: 'critical',
    done: false,
    steps: [
      'Go to fmjfee.com — the only official SEVIS payment site. Type it directly in your browser; do not click links from emails.',
      'You need your SEVIS ID number, printed on your I-20. Complete the I-20 step before this one.',
      'The fee is $350 for F-1 students. Do not pay any other amount — $200 and $220 figures still circulate on unofficial sites.',
      'Download and save your I-901 payment confirmation receipt immediately after payment.',
      'Allow at least 3 business days for the payment to process before your visa appointment date.',
      'Bring your printed confirmation to the visa interview.',
    ],
    whatToGather: [
      'I-20 document — your SEVIS ID is printed at the top',
      'Credit or debit card',
      'Passport',
    ],
    ifWrongGoesWrong: 'If you paid on an unofficial site, pay again on fmjfee.com immediately and dispute the fraudulent charge with your bank. Contact your DSO to document what happened — they can sometimes provide a supporting letter for your visa interview explaining the situation.',
    peerInsight: '"Students from my country were targeted by a fake SEVIS payment site that looked identical to the real one. Only fmjfee.com is valid. Save the URL before you need it." — International student, RISD',
    ai: 'The most common SEVIS error is paying on an unofficial site. Fraudulent SEVIS payment sites are designed to look identical to fmjfee.com and appear in paid search results. The official URL is fmjfee.com. Bookmark it now.',
  },

  visaapp: {
    title: 'Complete DS-160 and book your visa interview',
    category: 'visa',
    consequence: 'Visa appointments at peak season book out 60–90 days in advance. Missing the booking window can delay your arrival past the start of classes.',
    daysUntil: 21,
    dependsOn: ['i20', 'sevis'],
    urgency: 'soon',
    done: false,
    steps: [
      'Complete the DS-160 nonimmigrant visa application at ceac.state.gov. Save your application ID — you need it to retrieve the form if your session times out.',
      'Book your visa appointment through your country\'s U.S. embassy or consulate website. Select F-1 student visa.',
      'Pay the MRV visa application fee — currently $185. Keep the receipt.',
      'Prepare your interview documents: DS-160 confirmation, appointment confirmation, SEVIS fee receipt, I-20, acceptance letter, financial proof, passport, and one passport photo.',
      'At the interview: answer clearly and briefly. Common questions are your major, why you chose this school, and your plans after graduation. Practice 2–3 sentence answers.',
      'After approval, your passport will be retained for visa stamping and typically returned within 5–10 business days.',
    ],
    whatToGather: [
      'I-20',
      'SEVIS fee receipt (I-901 confirmation)',
      'Acceptance letter',
      'Financial proof — bank statement showing sufficient funds',
      'Passport valid for at least 6 months beyond your intended stay',
      'One passport photo, 2x2 inches, white background',
    ],
    ifWrongGoesWrong: 'If your visa is denied, ask the officer for the specific reason in writing before leaving the consulate. Most F-1 denials are due to incomplete financial documentation or the officer\'s concern that you do not intend to return home after your studies. Consult your DSO before reapplying — they have seen these situations before.',
    peerInsight: '"Book your appointment the day your I-20 arrives. In summer, appointments at some consulates were booking 10 weeks out. I almost missed my program start date." — International student, Columbia',
    ai: 'Processing time varies significantly by country. India, China, Mexico, Brazil, and Nigeria historically have the longest appointment wait times — often 60–90 days at peak season. Book your appointment as soon as your SEVIS fee confirmation arrives, not after you finish your DS-160.',
  },

  healthinsurance: {
    title: 'Enroll in or waive student health insurance',
    category: 'health',
    consequence: 'If you miss the waiver deadline, you are automatically enrolled and charged for the school plan — typically $1,500–$3,000 per year. If you miss enrollment, you have no coverage until next open enrollment.',
    daysUntil: 45,
    dependsOn: ['enrolldeposit'],
    urgency: 'upcoming',
    done: false,
    steps: [
      'Check your student account portal for a "Health Insurance" section — most schools auto-enroll you and charge the fee unless you actively opt out.',
      'If you have qualifying coverage (a parent\'s plan if you are under 26, or your own), submit a waiver before the deadline with your insurance card information.',
      'If you need coverage, review the school plan: check the network, deductible, and whether the campus health center is in-network.',
      'International students often cannot waive the school plan unless they have U.S.-based coverage equivalent to the school standard. Confirm the requirement with your ISS office.',
      'Set a calendar reminder for the waiver deadline — it is usually within the first 2–3 weeks of the semester.',
    ],
    whatToGather: [
      'Current insurance card and policy details (if waiving)',
      'Insurance policy number and group number',
      'Student health insurance portal login',
    ],
    ifWrongGoesWrong: 'If you miss the waiver deadline, contact the student health insurance office immediately. Some schools grant a one-time exception within a short window after the deadline. It is worth a phone call. Document the date and time you contacted them in case you need to escalate.',
    peerInsight: '"I did not know I was automatically enrolled until I saw a $2,400 charge on my student bill. File the waiver on your first day if you have your own insurance." — Transfer student, RISD',
    ai: 'International students on F-1 visas are typically required to carry health insurance as a condition of their visa status. Most schools mandate the school plan unless the student can prove equivalent U.S.-based coverage. Check your school\'s specific waiver eligibility criteria — they vary significantly.',
  },

  credittransfer: {
    title: 'Advocate for your transfer credits',
    category: 'academic',
    consequence: 'Credits default to "general elective" status, potentially adding a full semester or more to your degree timeline.',
    daysUntil: 60,
    dependsOn: ['enrolldeposit'],
    urgency: 'upcoming',
    done: false,
    steps: [
      'Request your official credit evaluation report from the Registrar — it shows which credits transferred and in what category.',
      'Identify any credits marked "general elective" that you believe should count toward major or general education requirements.',
      'Gather syllabi and course descriptions from each contested course — these are your primary evidence for equivalency.',
      'Email the department chair (not admin staff) of the relevant department: attach syllabi, list learning outcomes, and explain why the course maps to the requirement.',
      'Follow up in person during office hours if no response within 7 business days.',
      'If the department denies the appeal, escalate to the Dean of Academic Affairs with the same documentation.',
    ],
    whatToGather: [
      'Official credit evaluation report from the Registrar',
      'Syllabi from all transferred courses',
      'Course catalog from your previous institution',
      'Degree requirements checklist for your new program',
    ],
    ifWrongGoesWrong: 'If all department-level appeals fail, file a formal academic petition with the Dean of Students office. Document every step of your outreach with dates and names. The formal petition process is slower but is independent of the department that denied you.',
    peerInsight: '"Nobody told me I needed to advocate for my credits after admission. I assumed the school handled it. I lost an entire semester to elective credits because I waited." — Kathryn, transfer student, Cal State to RISD',
    ai: 'Transfer credit disputes are one of the most consequential and least communicated parts of the transfer experience. Most schools only allow appeals within the first semester — after that, exceptions require Dean-level approval. Start this process before classes begin.',
  },

}
