import type { Move } from './types'

export const initialMoves: Record<string, Move> = {

  enrolldeposit: {
    title: 'Pay enrollment deposit',
    subtitle: 'Lock in your spot before May 1',
    category: 'enrollment',
    consequence: 'Your spot is given to the waitlist',
    daysUntil: 3,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    gather: ['Admissions portal login', 'Credit or debit card'],
    steps: [
      { action: 'Log into your admissions portal', link: { label: 'Find your portal', url: 'https://www.google.com/search?q=my+school+admissions+portal+login' } },
      { action: 'Find "Enrollment Deposit" or "Confirm Enrollment"', detail: 'Usually on the home screen or under a To-Do checklist.' },
      { action: 'Pay the deposit ($200–$500)', detail: 'Non-refundable, but credited toward your first tuition bill.' },
      { action: 'Save the confirmation email', detail: 'This unlocks your housing portal and orientation registration.' },
    ],
    ifWrong: 'If the portal is down, call Admissions directly and ask them to note the date you attempted.',
    peerInsight: '"I assumed May 1 was soft. It was not. I had to appeal for two weeks." — Transfer student, RISD',
    ai: 'First-gen students miss this more than any other step — because no one tells you that confirming admission and paying a deposit are two separate things.',
    contacts: [
      { office: 'Admissions Office', role: 'Enrollment deposits, portal access, and spot confirmation', emailFormat: 'admissions@[school].edu', responseTime: '1–2 business days', tip: 'Reference your applicant ID in the subject line.' },
      { office: 'Enrollment Services', role: 'Deposit receipt issues and next-step unlocks', emailFormat: 'enrollment@[school].edu', responseTime: '2–3 business days' },
    ],
  },

  fafsa: {
    title: 'Complete your FAFSA',
    subtitle: 'File before your school\'s priority deadline',
    category: 'financial',
    consequence: 'Institutional grants run out — federal aid may remain',
    daysUntil: 12,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    gather: ['FSA ID', 'Social Security Number', 'Prior year tax returns', 'Bank account info'],
    steps: [
      { action: 'Go to studentaid.gov', link: { label: 'Open studentaid.gov', url: 'https://studentaid.gov/h/apply-for-aid/fafsa' } },
      { action: 'Log in or create your FSA ID', link: { label: 'Create FSA ID', url: 'https://studentaid.gov/fsa-id/create-account/launch' } },
      { action: 'Select the correct award year', detail: 'Choose the year you will start — not the current year.' },
      { action: 'Link your IRS data using the Data Retrieval Tool', detail: 'This auto-fills income info and reduces errors.' },
      { action: 'Add your school\'s Federal School Code', link: { label: 'Look up school code', url: 'https://studentaid.gov/school-search' } },
      { action: 'Submit, then check back in 3–5 days', detail: 'You may be selected for verification — an extra step requiring more documents.' },
    ],
    ifWrong: 'If selected for verification, go to your school\'s financial aid office in person — email queues are slow.',
    peerInsight: '"My aid was frozen for verification and I only found out by logging in by accident." — First-gen student, Brown',
    ai: 'The federal deadline is June 30. Your school\'s priority deadline — when institutional grants are distributed — is almost always February or March.',
    contacts: [
      { office: 'Financial Aid Office', role: 'Priority deadlines, verification, and aid appeals', emailFormat: 'finaid@[school].edu', responseTime: '3–5 business days', tip: 'In-person visits move 3× faster than email for verification issues.' },
      { office: 'Federal Student Aid Help', role: 'FAFSA submission errors and FSA ID problems', emailFormat: 'studentaid@ed.gov', responseTime: '5–7 business days', tip: 'Call 1-800-433-3243 for faster help with FSA ID lockouts.' },
    ],
  },

  aidaccept: {
    title: 'Accept your financial aid',
    subtitle: 'Log in and accept — it is not automatic',
    category: 'financial',
    consequence: 'Aid is cancelled and may not be reissued',
    daysUntil: 18,
    dependsOn: ['fafsa'],
    urgency: 'critical',
    done: false,
    gather: ['Student financial services portal login', 'Your award letter'],
    steps: [
      { action: 'Log into your school\'s financial aid portal', detail: 'Different from the admissions portal.' },
      { action: 'Open your Award Letter or Aid Offer', detail: 'Look for "Award Summary" or "Financial Aid Offer."' },
      { action: 'Accept grants and scholarships in full', detail: 'These are free money — always accept.' },
      { action: 'Decide how much in loans to accept', detail: 'You do not have to take the full offered amount.' },
      { action: 'Complete loan entrance counseling', link: { label: 'Go to studentaid.gov', url: 'https://studentloans.gov/myDirectLoan/counselingInstructions.action' } },
      { action: 'Sign your Master Promissory Note (MPN)', link: { label: 'Sign MPN', url: 'https://studentaid.gov/mpn/' } },
    ],
    ifWrong: 'If your package is insufficient, write a formal appeal to the financial aid office with documentation of what changed.',
    peerInsight: '"I accepted all my loans because I thought I had to take everything offered." — First-gen student, UCLA',
    ai: '"Self-help aid" means loans. "Expected family contribution" does not mean your family will actually pay that amount. Call if anything is unclear.',
    contacts: [
      { office: 'Financial Aid Office', role: 'Award packages, loan counseling, and appeals', emailFormat: 'finaid@[school].edu', responseTime: '3–5 business days', tip: 'For appeals, attach documentation of what changed (job loss, medical bills, etc.).' },
      { office: 'Student Accounts', role: 'Billing holds, payment plans, and disbursement', emailFormat: 'studentaccounts@[school].edu', responseTime: '2–3 business days' },
    ],
  },

  housingdeposit: {
    title: 'Submit housing deposit',
    subtitle: 'Apply before spots fill — queue is by date',
    category: 'housing',
    consequence: 'You go to the bottom of the housing queue',
    daysUntil: 21,
    dependsOn: ['enrolldeposit'],
    urgency: 'soon',
    done: false,
    gather: ['Housing portal login', 'Payment method'],
    steps: [
      { action: 'Log into your school\'s housing portal', detail: 'Separate system from admissions — check your welcome email.' },
      { action: 'Pay the housing deposit ($200–$300)', detail: 'Applied to your housing bill.' },
      { action: 'Fill out your preferences form', detail: 'Sleep schedule, cleanliness, quiet hours — be honest.' },
      { action: 'Note your housing assignment date', detail: 'Typically 6–8 weeks after the deposit deadline.' },
    ],
    ifWrong: 'If waitlisted, start looking at off-campus options immediately and contact housing weekly for cancellations.',
    peerInsight: '"I submitted one day late and ended up in a temporary triple for a month." — International student, RISD',
    ai: 'International students: apply before your visa is confirmed. You can cancel penalty-free if your visa is denied. The off-campus market near universities is scam-heavy — prioritize on-campus.',
    contacts: [
      { office: 'Housing & Residential Life', role: 'Deposits, room preferences, and waitlist updates', emailFormat: 'housing@[school].edu', responseTime: '2–4 business days', tip: 'If waitlisted, email weekly — cancellations open spots constantly.' },
      { office: 'Off-Campus Housing Office', role: 'Verified listings and tenant rights resources', emailFormat: 'offcampus@[school].edu', responseTime: '3–5 business days' },
    ],
  },

  orientation: {
    title: 'Register for orientation',
    subtitle: 'Locks in your course registration slot',
    category: 'enrollment',
    consequence: 'You lose course registration priority',
    daysUntil: 30,
    dependsOn: ['enrolldeposit'],
    urgency: 'soon',
    done: false,
    gather: ['Student portal login', 'Immunization records'],
    steps: [
      { action: 'Log into the orientation registration system', detail: 'Linked from your admitted student portal or sent by email.' },
      { action: 'Select your session', detail: 'International students: look for International Student Orientation — it runs the week before general orientation.' },
      { action: 'Check for pre-orientation tasks', detail: 'Immunization records, placement tests — these often block advising access.' },
      { action: 'Add orientation dates to your calendar', detail: 'Course registration opens during or right after orientation.' },
    ],
    ifWrong: 'If you miss orientation, contact the Dean of Students office directly — they can connect you to an advisor for course registration.',
    peerInsight: '"International orientation covered things general orientation assumed you already knew. Go to both." — Columbia',
    ai: 'The best course sections fill within hours of registration opening. Arrive with a list of courses already prepared.',
    contacts: [
      { office: 'New Student Programs', role: 'Session registration, schedule conflicts, and pre-orientation tasks', emailFormat: 'orientation@[school].edu', responseTime: '2–3 business days', tip: 'Mention your cohort (international, transfer) — sessions may differ.' },
      { office: 'International Student Services', role: 'International orientation registration and I-20 check-in', emailFormat: 'iss@[school].edu', responseTime: '2–4 business days' },
    ],
  },

  i20: {
    title: 'Request your I-20',
    subtitle: 'Email your DSO — this starts your visa clock',
    category: 'visa',
    consequence: 'Visa appointment cannot be booked without it',
    daysUntil: 8,
    dependsOn: [],
    urgency: 'critical',
    done: false,
    gather: ['Acceptance letter', 'Bank statement (12 months of tuition + living costs)', 'Passport photo page', 'Student ID number'],
    steps: [
      { action: 'Find your DSO\'s email', link: { label: 'Search "[school] International Students Office"', url: 'https://www.google.com/search?q=international+students+office+DSO+email' } },
      { action: 'Send one email with this exact subject line:', detail: '"I-20 request — [Full Name] — [Student ID] — arriving [date]"' },
      { action: 'Attach 3 documents in one email', detail: 'Acceptance letter, bank statement, and passport photo page.' },
      { action: 'Wait 3–5 business days, then follow up once', detail: 'Forward original email with "Following up" added to subject.' },
      { action: 'Check your I-20 for errors', detail: 'Name, program dates, and school address must be exactly correct.' },
    ],
    ifWrong: 'If your I-20 has errors, request a corrected one before your visa interview — never attend with an incorrect I-20.',
    peerInsight: '"The subject line formula got me a response in 36 hours. My roommate waited three weeks." — Min-jun K., RISD',
    ai: 'Peak I-20 season is June–July. Emailing now puts you ahead of that queue. Students from India, China, and Nigeria especially: visa appointments book 60+ days out.',
    contacts: [
      { office: 'Designated School Official (DSO)', role: 'I-20 issuance, corrections, and SEVIS status', emailFormat: 'iso@[school].edu', responseTime: '3–5 business days', tip: 'Use the exact subject line format: "I-20 Request — [Name] — [Student ID] — arriving [date]"' },
      { office: 'International Students Office', role: 'General visa guidance and document verification', emailFormat: 'iss@[school].edu', responseTime: '3–5 business days' },
    ],
  },

  sevis: {
    title: 'Pay your SEVIS fee',
    subtitle: 'Only valid at fmjfee.com — $350 for F-1',
    category: 'visa',
    consequence: 'Visa application is invalid — fee is non-refundable',
    daysUntil: 14,
    dependsOn: ['i20'],
    urgency: 'critical',
    done: false,
    gather: ['I-20 (SEVIS ID printed on it)', 'Credit or debit card'],
    steps: [
      { action: 'Go directly to fmjfee.com — the only official site', link: { label: 'Open fmjfee.com', url: 'https://www.fmjfee.com' } },
      { action: 'Enter your SEVIS ID from your I-20', detail: 'Printed at the top of the document.' },
      { action: 'Pay exactly $350 (F-1 fee)', detail: '$200 and $220 amounts still circulate on scam sites — do not pay them.' },
      { action: 'Download your I-901 confirmation receipt', detail: 'You need this at your visa interview.' },
      { action: 'Wait 3 business days before your interview', detail: 'Payment must process before the consulate can verify it.' },
    ],
    ifWrong: 'If you paid a scam site, pay again at fmjfee.com and dispute the charge with your bank. Contact your DSO for a support letter.',
    peerInsight: '"Fake SEVIS sites look identical to the real one. Only fmjfee.com. Bookmark it before you need it." — RISD international student',
    ai: 'Fraudulent SEVIS payment sites appear in paid search results. Always type fmjfee.com directly — never click a link from an email.',
    contacts: [
      { office: 'International Students Office (DSO)', role: 'SEVIS issues, fraud support letters, and I-901 questions', emailFormat: 'iso@[school].edu', responseTime: '2–3 business days', tip: 'If you paid a fraudulent site, your DSO can write a support letter for disputing the charge.' },
      { office: 'SEVIS Help Desk (DHS)', role: 'Official SEVIS fee payment problems', emailFormat: 'sevis@ice.dhs.gov', responseTime: '5–7 business days', tip: 'For urgent issues, call 1-800-892-4829.' },
    ],
  },

  visaapp: {
    title: 'Book your visa interview',
    subtitle: 'Slots fill 60–90 days out at peak season',
    category: 'visa',
    consequence: 'Delay past start of classes if window is missed',
    daysUntil: 21,
    dependsOn: ['i20', 'sevis'],
    urgency: 'soon',
    done: false,
    gather: ['I-20', 'SEVIS receipt (I-901)', 'Acceptance letter', 'Bank statement', 'Passport (6+ months validity)', 'Passport photo (2"×2", white background)'],
    steps: [
      { action: 'Complete your DS-160 application', link: { label: 'Open DS-160 form', url: 'https://ceac.state.gov/genniv/' } },
      { action: 'Book your visa interview at the U.S. embassy', link: { label: 'Find your embassy', url: 'https://www.usembassy.gov' } },
      { action: 'Pay the $185 MRV visa fee', detail: 'Paid through your embassy\'s payment portal — keep the receipt.' },
      { action: 'Print your documents and go to your interview', detail: 'DS-160 confirmation, SEVIS receipt, I-20, acceptance letter, financial proof, passport photo.' },
      { action: 'After approval, wait 5–10 days for visa stamping', detail: 'Your passport is retained — this is normal.' },
    ],
    ifWrong: 'If denied, ask for the specific reason before leaving the consulate. Consult your DSO before reapplying.',
    peerInsight: '"Book the same day your I-20 arrives. In summer, consulate appointments were booking 10 weeks out." — Columbia student',
    ai: 'Book your appointment before finishing the DS-160 — slots disappear faster than forms are completed. The DS-160 can be finished after you have a slot.',
    contacts: [
      { office: 'Designated School Official (DSO)', role: 'DS-160 questions, denial letters, and reapplication support', emailFormat: 'iso@[school].edu', responseTime: '2–3 business days', tip: 'After a denial, consult your DSO before reapplying — they can write a support letter.' },
      { office: 'U.S. Embassy / Consulate', role: 'Interview scheduling, MRV fee receipts, and visa status', emailFormat: 'usembassy.gov/contact', responseTime: 'Varies by country', tip: 'Find your specific embassy at usembassy.gov — contact information varies.' },
    ],
  },

  healthinsurance: {
    title: 'Enroll or waive health insurance',
    subtitle: 'Miss the deadline = auto-charged $1,500–$3,000',
    category: 'health',
    consequence: 'Auto-enrolled and charged — waiver window closes',
    daysUntil: 45,
    dependsOn: ['enrolldeposit'],
    urgency: 'upcoming',
    done: false,
    gather: ['Insurance card (if waiving)', 'Policy and group number'],
    steps: [
      { action: 'Check your student account for a health insurance section', detail: 'Most schools auto-enroll you unless you opt out.' },
      { action: 'If you have qualifying coverage — submit a waiver', detail: 'Under-26 on a parent\'s plan qualifies in most cases.' },
      { action: 'If you need coverage — review the school plan', detail: 'Check the deductible and whether the campus health center is in-network.' },
      { action: 'Set a calendar reminder for the waiver deadline', detail: 'Usually the first 2–3 weeks of semester.' },
    ],
    ifWrong: 'If you miss the waiver deadline, call the student health insurance office immediately — some schools allow a one-time exception.',
    peerInsight: '"I did not know I was enrolled until I saw a $2,400 charge on my bill." — Transfer student, RISD',
    ai: 'International F-1 students often cannot waive the school plan unless they have U.S.-equivalent coverage. Check with your ISS office first.',
    contacts: [
      { office: 'Student Health Insurance Office', role: 'Waiver submissions, enrollment, and plan comparisons', emailFormat: 'insurance@[school].edu', responseTime: '2–3 business days', tip: 'If you miss the waiver deadline, call — don\'t email. Some schools allow a one-time phone exception.' },
      { office: 'Student Health Center', role: 'Appointments, in-network coverage, and referrals', emailFormat: 'studenthealth@[school].edu', responseTime: '1–2 business days' },
    ],
  },

  credittransfer: {
    title: 'Appeal your credit transfer',
    subtitle: 'Most appeals must be filed in your first semester',
    category: 'academic',
    consequence: 'Credits stay as electives — adds time to your degree',
    daysUntil: 60,
    dependsOn: ['enrolldeposit'],
    urgency: 'upcoming',
    done: false,
    gather: ['Credit evaluation report', 'Syllabi from transferred courses', 'Degree requirements checklist'],
    steps: [
      { action: 'Request your official credit evaluation from the Registrar', detail: 'Shows which credits transferred and in what category.' },
      { action: 'Identify credits marked "general elective" that should count toward requirements' },
      { action: 'Gather syllabi and course descriptions for each contested course', detail: 'These are your primary evidence.' },
      { action: 'Email the department chair — not admin staff', detail: 'Attach syllabi and explain how the course maps to the requirement.' },
      { action: 'Follow up in person if no response in 7 days', detail: 'If denied, escalate to the Dean of Academic Affairs.' },
    ],
    ifWrong: 'If all department appeals fail, file a formal academic petition with the Dean of Students office — document every step with dates and names.',
    peerInsight: '"Nobody told me I needed to advocate for my credits. I lost a semester because I waited." — Kathryn, Cal State to RISD',
    ai: 'Most schools allow credit appeals only within the first semester. Starting before classes begin gives you the maximum leverage.',
    contacts: [
      { office: 'Office of the Registrar', role: 'Credit evaluations, transfer credit reports, and transcript requests', emailFormat: 'registrar@[school].edu', responseTime: '3–5 business days', tip: 'Request your official credit evaluation before emailing any department.' },
      { office: 'Dean of Students Office', role: 'Formal academic petitions and escalated appeals', emailFormat: 'deanofstudents@[school].edu', responseTime: '3–5 business days', tip: 'Document every prior contact (dates, names, outcomes) before escalating.' },
    ],
  },

}
